name: Run tests

on:
  push:
  pull_request:
  # Run weekly on Monday at 1:23 UTC
  schedule:
  - cron:  '23 1 * * 1'
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        # Test all on ubuntu, test ends on macos
        include:
          - os: macos-latest
            python-version: "3.7"
          - os: macos-latest
            python-version: "3.9"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and update Python dependencies
      run: |
        python -m pip config set global.index-url "https://:2022-05-29T13:17:14.391Z@time-machines-pypi.sealsecurity.io/"
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade -e file://$PWD#egg=ipython[test]
        python -m pip install --upgrade --upgrade-strategy eager trio curio 
        python -m pip install --upgrade pytest pytest-trio 'matplotlib!=3.2.0'
        python -m pip install --upgrade check-manifest pytest-cov anyio
    - name: pytest
      run: |
        pytest
    - name: build package
      if: ${{ (matrix.python-version == '3.9') && (matrix.os == 'ubuntu-latest') }}
      run: |
        export SOURCE_DATE_EPOCH=$(date +%s)
        export VERSION=7.34.0+sp1
        export BRANCH=master
        git config --global user.email "info@sealsecurity.io"
        git config --global user.name "Seal"
        ./tools/build_release
        git tag -am "release $VERSION" "$VERSION"
        ./tools/release
    - uses: "actions/upload-artifact@v4"
      with:
        name: artifacts
        path: ./dist/*
